name: deploy
on:
  push:
    branches:
    - main
    - release/*
jobs:
  my_job:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.7.0
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0
      with: 
        node-version: '17.x'
    - name: install pnpm
      run: npm install pnpm -g    
    - name: install dep
      run: pnpm install
    - name: build app
      run: pnpm run build
    - name: scp files to linux
      uses: appleboy/scp-action@master
      with: 
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USERNAME }}
        password: ${{ secrets.REMOTE_PASSWORLD }}
        port: ${{ secrets.REMOTE_PORT }}
        source: "dist/"
        target: ${{ secrets.REMOTE_TARGET }}
        
      
      
    
